# Generated by Django 5.2.9 on 2026-09-12 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_number', models.CharField(blank=True, max_length=64, verbose_name='شماره بایگانی')),
                ('loan_type', models.CharField(blank=True, choices=[('LOANED', 'امانی'), ('INTERNAL', 'داخلی')], max_length=16, verbose_name='امانی/داخلی')),
                ('appraisal_date', models.DateField(verbose_name='تاریخ کارشناسی')),
                ('artwork_type', models.CharField(blank=True, choices=[('MANUSCRIPT_BOOK', 'کتاب خطی'), ('LITHOGRAPH_BOOK', 'کتاب چاپ سنگی'), ('MANUSCRIPT_FOLIO', 'قطعه خطی'), ('PAINTING', 'تابلو نقاشی'), ('MINIATURE', 'قطعه مینیاتور'), ('ILLUMINATION', 'قطعه تذهیب'), ('PAPIER_MACHE_PENCASE', 'قلمدان پاپیه ماشه'), ('ASTROLABE', 'اسطرلاب'), ('METAL_GLOBE', 'کره زمین فلزی'), ('CARPET', 'فرش'), ('HANDWOVEN', 'دست بافت'), ('QALAMKAR_FABRIC', 'پارچه قلمکار'), ('METAL_ARTIFACT', 'مصنوعات فلزی'), ('PHOTOGRAPH', 'عکس'), ('JEWELRY', 'زیورآلات')], max_length=32, verbose_name='نوع اثر')),
                ('content_subject', models.CharField(blank=True, choices=[('QURAN', 'قرآن'), ('PRAYERS', 'ادعیه'), ('ASTRONOMY', 'نجوم'), ('MEDICINE', 'پزشکی'), ('POETRY', 'شعر'), ('PHILOSOPHY', 'فلسفه'), ('HISTORY', 'تاریخ'), ('GEOGRAPHY', 'جغرافیا'), ('GENEALOGY', 'احراز'), ('BIBLE', 'انجیل'), ('TORAH', 'تورات'), ('MYSTICISM', 'عرفان')], max_length=32, verbose_name='موضوع اثر')),
                ('inscribed_date_text', models.CharField(blank=True, max_length=128, verbose_name='تاریخ ذکر شده در اثر')),
                ('calendar_type', models.CharField(blank=True, choices=[('SHAMSI', 'هجری شمسی'), ('QAMARI', 'هجری قمری'), ('MILADI', 'میلادی')], max_length=16, verbose_name='نوع تقویم')),
                ('historical_period', models.CharField(blank=True, max_length=128, verbose_name='قرن/دوره تاریخی')),
                ('artist_or_scribe_name', models.CharField(blank=True, max_length=255, verbose_name='نام هنرمند/کاتب')),
                ('historical_match_status', models.CharField(blank=True, choices=[('CONFIRMED', 'تایید می\u200cشود'), ('PROBABLE', 'احتمالی'), ('REJECTED', 'مردود')], max_length=16, verbose_name='مطابقت تاریخی با اصل اثر')),
                ('attribution_certainty', models.CharField(blank=True, choices=[('DEFINITE', 'قطعی'), ('ATTRIBUTED', 'منسوب'), ('PROBABLE', 'احتمالی'), ('UNKNOWN', 'ناشناس')], max_length=16, verbose_name='انتساب اثر به هنرمند')),
                ('signature_location', models.CharField(blank=True, max_length=255, verbose_name='محل امضاء در اثر')),
                ('language', models.CharField(blank=True, choices=[('PERSIAN', 'فارسی'), ('ARABIC', 'عربی'), ('LATIN', 'لاتین'), ('HEBREW', 'عبری'), ('OTHER', 'دیگر')], max_length=16, verbose_name='زبان')),
                ('language_other', models.CharField(blank=True, max_length=64, verbose_name='زبان (سایر)')),
                ('script', models.CharField(blank=True, choices=[('TALIQ', 'تعلیق'), ('RIQA', 'رقاع'), ('REYHAN', 'ریحان'), ('TAWQI', 'توقیع'), ('THULUTH', 'ثلث'), ('NASKH', 'نسخ'), ('KUFI_EASTERN', 'کوفی مشرقی'), ('KUFI_WESTERN', 'کوفی مغربی'), ('KUFI_EARLY', 'کوفی مبکر'), ('SHEKASTE_NASTALIQ', 'شکسته نستعلیق'), ('DIVANI', 'دیوانی'), ('OBSOLETE_SCRIPTS', 'خطوط منسوخ شده')], max_length=32, verbose_name='خط')),
                ('dimensions', models.CharField(blank=True, max_length=64, verbose_name='ابعاد (سانتی\u200cمتر)')),
                ('dimensions_with_frame', models.CharField(blank=True, max_length=64, verbose_name='ابعاد با قاب (سانتی\u200cمتر)')),
                ('dimensions_with_margin', models.CharField(blank=True, max_length=64, verbose_name='ابعاد با حاشیه (سانتی\u200cمتر)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن (کیلوگرم)')),
                ('material', models.CharField(blank=True, choices=[('PAPER', 'کاغذ'), ('PARCHMENT', 'پوست'), ('SILK', 'ابریشم'), ('LINEN', 'کتان'), ('BRASS', 'برنج'), ('SILVER', 'نقره'), ('PAPIER_MACHE', 'پاپیه ماشه'), ('WOOL_CASHMERE', 'پشم/کرک'), ('STEEL', 'فولاد'), ('WOOD', 'چوب'), ('GLASS', 'شیشه'), ('MIRROR', 'آینه')], max_length=32, verbose_name='جنس')),
                ('material_other', models.CharField(blank=True, max_length=64, verbose_name='جنس (سایر)')),
                ('pages_or_pieces_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد صفحات/قطعات')),
                ('ink_type', models.CharField(blank=True, choices=[('GOLD', 'طلا نویسی'), ('COLORED', 'رنگین نویسی'), ('BLACK', 'مرکب سیاه'), ('LAPIS', 'لاجورد'), ('WHITE_LEAD', 'سفیدآب'), ('OTHER', 'دیگر')], max_length=16, verbose_name='نوع مرکب')),
                ('ink_type_other', models.CharField(blank=True, max_length=64, verbose_name='نوع مرکب (سایر)')),
                ('illumination_technique', models.CharField(blank=True, choices=[('HALKARI', 'حلکاری'), ('TASHIR', 'تشعیر'), ('TOOTH_CARVING', 'دندان موشی'), ('PARDAZ', 'پرداز'), ('MOHARAR', 'محرر'), ('SIAH_GHALAM', 'سیاه قلم'), ('OTHER', 'دیگر')], max_length=16, verbose_name='تکنیک تذهیب/نگاره')),
                ('illumination_technique_other', models.CharField(blank=True, max_length=64, verbose_name='تکنیک تذهیب/نگاره (سایر)')),
                ('painting_type', models.CharField(blank=True, choices=[('FLOWER_BIRD', 'گل و مرغ'), ('ESLIMI', 'اسلیمی'), ('KHATAYI', 'خطایی'), ('LACHAK_TORANJ', 'لچک و ترنج'), ('MINIATURE', 'مینیاتور'), ('HALKARI', 'حلکاری'), ('OTHER', 'دیگر')], max_length=16, verbose_name='نوع نگاره')),
                ('painting_type_other', models.CharField(blank=True, max_length=64, verbose_name='نوع نگاره (سایر)')),
                ('cover_type', models.CharField(blank=True, choices=[('MOROCCO_LEATHER', 'چرم میشن'), ('SAGHRI_LEATHER', 'چرم ساغری'), ('COWHIDE_LEATHER', 'چرم گاوی'), ('PYROGRAPHY', 'سوختکاری'), ('PYROGRAPHY_INLAY', 'سوخت معرق'), ('LACQUER', 'جلد لاکی'), ('WOODEN', 'چوبی'), ('GILDED_LEATHER', 'چرم طلاکاری/سوخت')], max_length=32, verbose_name='نوع جلد')),
                ('warp_material', models.CharField(blank=True, choices=[('SILK', 'ابریشم'), ('CASHMERE', 'کرک'), ('WOOL', 'پشم'), ('COTTON', 'پنبه'), ('OTHER', 'دیگر')], max_length=16, verbose_name='جنس تار')),
                ('warp_material_other', models.CharField(blank=True, max_length=64, verbose_name='جنس تار (سایر)')),
                ('weft_material', models.CharField(blank=True, choices=[('SILK', 'ابریشم'), ('CASHMERE', 'کرک'), ('WOOL', 'پشم'), ('COTTON', 'پنبه'), ('OTHER', 'دیگر')], max_length=16, verbose_name='جنس پود')),
                ('weft_material_other', models.CharField(blank=True, max_length=64, verbose_name='جنس پود (سایر)')),
                ('fabric_type', models.CharField(blank=True, choices=[('SILK', 'ابریشم'), ('BROCADE', 'زربافت'), ('CALICO', 'متقال'), ('VELVET', 'مخمل'), ('COTTON', 'پنبه'), ('PAISLEY', 'بته جقه'), ('OTHER', 'دیگر')], max_length=16, verbose_name='نوع پارچه')),
                ('fabric_type_other', models.CharField(blank=True, max_length=64, verbose_name='نوع پارچه (سایر)')),
                ('knot_type', models.CharField(blank=True, choices=[('DOUBLE', 'جفتی'), ('OTHER', 'دیگر')], max_length=16, verbose_name='نوع گره')),
                ('knot_type_other', models.CharField(blank=True, max_length=64, verbose_name='نوع گره (سایر)')),
                ('design_pattern', models.CharField(blank=True, choices=[('LACHAK_TORANJ', 'لچک ترنج'), ('FISH_PATTERN', 'نقشه ماهی'), ('BIBI_BAFT', 'بی\u200cبی بافت'), ('AROOS_BAFT', 'عروس بافت'), ('LEILI_MAJNUN', 'لیلی مجنون'), ('OTHER', 'دیگر')], max_length=16, verbose_name='طرح نقشه')),
                ('design_pattern_other', models.CharField(blank=True, max_length=64, verbose_name='طرح نقشه (سایر)')),
                ('health_status', models.CharField(blank=True, choices=[('MINOR_DAMAGE', 'آسیب جزئی'), ('FULL_HEALTH', 'سلامت کامل'), ('SEVERE_RISK', 'در معرض آسیب جدی'), ('OTHER', 'دیگر')], max_length=16, verbose_name='وضعیت سلامت اثر')),
                ('health_status_other', models.CharField(blank=True, max_length=64, verbose_name='وضعیت سلامت اثر (سایر)')),
                ('needs_restoration', models.BooleanField(default=False, verbose_name='نیاز به مرمت دارد')),
                ('needs_restoration_part', models.CharField(blank=True, max_length=255, verbose_name='نیاز به مرمت - کدام قسمت')),
                ('has_previous_restoration', models.BooleanField(default=False, verbose_name='مرمت قبلی دارد')),
                ('previous_restoration_part', models.CharField(blank=True, max_length=255, verbose_name='مرمت قبلی - کدام قسمت')),
                ('has_missing_pages', models.BooleanField(default=False, verbose_name='کمبود صفحات دارد')),
                ('missing_pages_part', models.CharField(blank=True, max_length=255, verbose_name='کمبود صفحات - کدام قسمت')),
                ('review_notes', models.TextField(blank=True, verbose_name='نکات قابل بررسی در مورد اثر')),
                ('introduction', models.TextField(blank=True, verbose_name='معرفی اثر')),
                ('historical_importance', models.TextField(blank=True, verbose_name='اهمیت تاریخی')),
                ('artistic_importance', models.TextField(blank=True, verbose_name='اهمیت هنری')),
                ('unique_features', models.TextField(blank=True, verbose_name='ویژگی\u200cهای منحصر به فرد')),
                ('expert_opinion', models.TextField(blank=True, verbose_name='نظر کارشناسی (تحلیل)')),
                ('references', models.TextField(blank=True, verbose_name='رفرنس\u200cها')),
                ('marginal_notes', models.TextField(blank=True, verbose_name='متن\u200cهای حاشیه\u200cای مهم')),
                ('seller_suggested_price_toman', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پیشنهادی فروشنده (تومان)')),
                ('estimated_price_min_toman', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت برآوردی کارشناسی - کمینه (تومان)')),
                ('estimated_price_max_toman', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت برآوردی کارشناسی - بیشینه (تومان)')),
                ('final_auction_price_toman', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت نهایی شرکت در حراج (تومان)')),
                ('final_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت نهایی به دلار')),
                ('usd_exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت روز دلار')),
                ('gold_18k_gram_price_toman', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت روز هر گرم طلای ۱۸ عیار (تومان)')),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='نام مالک/ارائه\u200cدهنده')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='تاریخ دریافت اثر برای کارشناسی')),
                ('final_result_summary', models.TextField(blank=True, verbose_name='نتیجه نهایی کارشناسی')),
                ('final_verdict', models.CharField(blank=True, choices=[('AUCTION_READY', 'قابل عرضه در حراج'), ('NOT_SUITABLE', 'غیر قابل عرضه'), ('NEEDS_FURTHER_REVIEW', 'نیازمند بررسی بیشتر')], max_length=32, verbose_name='نظر نهایی کارشناس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expert_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_appraisal', to='products.product', verbose_name='اثر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expert_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
            ],
            options={
                'verbose_name': 'کارشناسی اثر',
                'verbose_name_plural': 'کارشناسی\u200cهای آثار',
                'ordering': ('-appraisal_date', '-created_at'),
                'permissions': (('review_expert_appraisal', 'Can review expert appraisal'),),
            },
        ),
        migrations.CreateModel(
            name='DamageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('STAIN', 'لکه'), ('DISCOLORATION', 'تغییر رنگ'), ('TEAR', 'پارگی'), ('CORROSION', 'خوردگی'), ('CRACK', 'ترک'), ('MOISTURE', 'رطوبت'), ('MOLD', 'کپک'), ('INSECT_DAMAGE', 'آسیب حشرات'), ('DETACHMENT', 'افتادگی/جداشدگی'), ('FRAME_DAMAGE', 'آسیب قاب'), ('MISSING_PARTS', 'نقص قطعات')], max_length=32, verbose_name='نوع آسیب')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='محل آسیب')),
                ('severity', models.CharField(blank=True, max_length=255, verbose_name='میزان آسیب')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_assessments', to='expertise.expertappraisal', verbose_name='کارشناسی')),
            ],
            options={
                'verbose_name': 'ارزیابی آسیب',
                'verbose_name_plural': 'ارزیابی\u200cهای آسیب',
                'ordering': ('id',),
            },
        ),
    ]
