# Generated by Django 5.2.9 on 2026-09-14 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0002_expertappraisal_manager_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertappraisal',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='در صورت قفل شدن، اطلاعات کارشناسی جهت حفظ تاریخچه غیرقابل ویرایش می\u200cگردد.', verbose_name='قفل شده (تاریخچه غیرقابل تغییر)'),
        ),
        migrations.AddField(
            model_name='expertappraisal',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_expert_appraisals', to=settings.AUTH_USER_MODEL, verbose_name='ارجاع\u200cدهنده (مدیر)'),
        ),
        migrations.AddField(
            model_name='expertappraisal',
            name='status',
            field=models.CharField(choices=[('REFERRED', 'ارجاع داده شده'), ('IN_PROGRESS', 'در حال کارشناسی'), ('COMPLETED', 'تکمیل شده'), ('PENDING_MANAGER_APPROVAL', 'در انتظار تأیید مدیر'), ('APPROVED', 'تأیید شده'), ('REJECTED', 'رد شده')], db_index=True, default='REFERRED', max_length=32, verbose_name='وضعیت کارشناسی'),
        ),
    ]
