# Generated by Django 5.2.9 on 2026-09-15 08:25

from django.db import migrations


def copy_archive_number_to_product_code(apps, schema_editor):
    ExpertAppraisal = apps.get_model('expertise', 'ExpertAppraisal')
    Product = apps.get_model('products', 'Product')

    processed_product_ids = set()

    for appraisal in ExpertAppraisal.objects.exclude(archive_number='').iterator():
        if not appraisal.product_id or appraisal.product_id in processed_product_ids:
            continue

        archive_number = (appraisal.archive_number or '').strip()
        if not archive_number:
            continue

        product = Product.objects.filter(pk=appraisal.product_id).first()
        if product is None or product.product_code:
            processed_product_ids.add(appraisal.product_id)
            continue

        duplicate_exists = Product.objects.filter(
            source_type=product.source_type,
            product_code=archive_number,
        ).exclude(pk=product.pk).exists()
        if duplicate_exists:
            processed_product_ids.add(appraisal.product_id)
            continue

        product.product_code = archive_number
        product.save(update_fields=['product_code'])
        processed_product_ids.add(appraisal.product_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0003_expertappraisal_is_locked_and_more'),
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.RunPython(copy_archive_number_to_product_code, noop_reverse),
        migrations.RemoveField(
            model_name='expertappraisal',
            name='archive_number',
        ),
    ]
