# Generated by Django 5.2.9 on 2026-09-15 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0004_remove_expertappraisal_archive_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertappraisal',
            name='estimated_price_max_toman',
        ),
        migrations.RenameField(
            model_name='expertappraisal',
            old_name='estimated_price_min_toman',
            new_name='expert_suggested_price_toman',
        ),
        migrations.AlterField(
            model_name='expertappraisal',
            name='expert_suggested_price_toman',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پیشنهادی کارشناس (تومان)'),
        ),
    ]
