# Generated by Django 5.2.9 on 2026-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0005_remove_expertappraisal_estimated_price_max_toman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damageassessment',
            name='severity',
            field=models.CharField(blank=True, choices=[('MINOR', 'جزئی'), ('MODERATE', 'متوسط'), ('SEVERE', 'شدید'), ('CRITICAL', 'بحرانی'), ('OTHER', 'دیگر')], max_length=16, verbose_name='میزان آسیب'),
        ),
    ]
