# Generated by Django 5.1.6 on 2026-09-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0006_alter_damageassessment_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistOrScribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='نام هنرمند/کاتب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'هنرمند/کاتب',
                'verbose_name_plural': 'هنرمندان و کاتبان',
                'ordering': ('name',),
            },
        ),
    ]
