# Generated by Django 5.2.9 on 2026-09-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_operator_dashboard', 'Can view operator dashboard')], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
