from django.urls import path

from .views import (
    AuctionCreateView,
    AuctionDetailView,
    AuctionEditView,
    AuctionListView,
    AuctionSyncView,
    ProductApproveView,
    ProductCancelToggleView,
    ProductCreateView,
    ProductDashboardView,
    ProductDetailView,
    ProductEditView,
    ProductExpertFlagToggleView,
    ProductExpertReferralView,
    ProductImageDeleteView,
    ProductImageSetPrimaryView,
    ProductImageSortOrderUpdateView,
    ProductImageUploadView,
    ProductListView,
    ProductNotableToggleView,
    ProductPublishView,
    ProductRejectView,
    ProductReReviewView,
    ProductSubmitReviewView,
)

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('dashboard/', ProductDashboardView.as_view(), name='dashboard'),
    path('auctions/', AuctionListView.as_view(), name='auction_list'),
    path('auctions/create/', AuctionCreateView.as_view(), name='auction_create'),
    path('auctions/<int:id>/', AuctionDetailView.as_view(), name='auction_detail'),
    path('auctions/<int:id>/edit/', AuctionEditView.as_view(), name='auction_edit'),
    path('auctions/<int:id>/sync/', AuctionSyncView.as_view(), name='auction_sync'),
    path('<int:id>/', ProductDetailView.as_view(), name='detail'),
    path('<int:id>/submit-review/', ProductSubmitReviewView.as_view(), name='submit_review'),
    path('submit-review/<int:id>/', ProductSubmitReviewView.as_view()),
    path('<int:id>/refer-to-expert/', ProductExpertReferralView.as_view(), name='refer_to_expert'),
    path('<int:id>/approve/', ProductApproveView.as_view(), name='approve'),
    path('approve/<int:id>/', ProductApproveView.as_view()),
    path('<int:id>/reject/', ProductRejectView.as_view(), name='reject'),
    path('reject/<int:id>/', ProductRejectView.as_view()),
    path('<int:id>/publish/', ProductPublishView.as_view(), name='publish'),
    path('publish/<int:id>/', ProductPublishView.as_view()),
    path('<int:id>/re-review/', ProductReReviewView.as_view(), name='re_review'),
    path('re-review/<int:id>/', ProductReReviewView.as_view()),
    path('<int:id>/cancel-toggle/', ProductCancelToggleView.as_view(), name='cancel_toggle'),
    path('<int:id>/toggle-notable/', ProductNotableToggleView.as_view(), name='toggle_notable'),
    path('<int:id>/toggle-expert-flag/', ProductExpertFlagToggleView.as_view(), name='toggle_expert_flag'),
    path('<int:id>/images/upload/', ProductImageUploadView.as_view(), name='image_upload'),
    path(
        '<int:id>/images/<int:image_id>/primary/',
        ProductImageSetPrimaryView.as_view(),
        name='image_set_primary',
    ),
    path(
        '<int:id>/images/<int:image_id>/sort/',
        ProductImageSortOrderUpdateView.as_view(),
        name='image_sort_update',
    ),
    path(
        '<int:id>/images/<int:image_id>/delete/',
        ProductImageDeleteView.as_view(),
        name='image_delete',
    ),
    path('<int:id>/edit/', ProductEditView.as_view(), name='edit'),
    path('create/', ProductCreateView.as_view(), name='create'),
]
