# Generated by Django 5.2.9 on 2026-08-18 08:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import products.models
import products.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان اثر')),
                ('product_code', models.CharField(blank=True, db_index=True, help_text='برای جلوگیری از تداخل بین منابع مختلف، یکتایی کد در سطح source_type کنترل می\u200cشود.', max_length=64, null=True, verbose_name='کد اثر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت پیشنهادی')),
                ('suitable_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت مناسب')),
                ('suggestion_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='تاریخ پیشنهاد')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولید')),
                ('production_location', models.CharField(blank=True, max_length=255, verbose_name='محل تولید')),
                ('artist', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='هنرمند')),
                ('material', models.CharField(blank=True, max_length=255, verbose_name='متریال')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='موضوع')),
                ('usage', models.CharField(blank=True, max_length=255, verbose_name='کاربرد')),
                ('art_type', models.CharField(blank=True, max_length=255, verbose_name='نوع هنر')),
                ('suggested_by', models.CharField(blank=True, max_length=255, verbose_name='پیشنهاددهنده')),
                ('contact_method', models.CharField(blank=True, choices=[('WHATSAPP', 'واتساپ'), ('TELEGRAM', 'تلگرام'), ('EITAA', 'ایتا'), ('PHONE', 'تلفن'), ('IN_PERSON', 'حضوری'), ('WEBSITE', 'وب\u200cسایت'), ('OTHER', 'سایر')], max_length=32, verbose_name='روش پیشنهاد')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='انصراف')),
                ('is_notable', models.BooleanField(default=False, verbose_name='قابل توجه')),
                ('needs_expert_review', models.BooleanField(default=False, verbose_name='نیازمند کارشناسی')),
                ('source_type', models.CharField(choices=[('MANUAL', 'پیشنهاد دستی'), ('CHRISTIES', "Christie's"), ('SOTHEBYS', "Sotheby's"), ('OTHER_AUCTION', 'سایر حراجی\u200cها')], default='MANUAL', max_length=32, verbose_name='نوع منبع')),
                ('source_name', models.CharField(blank=True, max_length=255, verbose_name='نام منبع')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='آدرس منبع')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING_REVIEW', 'در انتظار بررسی'), ('APPROVED', 'تأیید شده'), ('PUBLISHED', 'منتشر شده'), ('REJECTED', 'رد شده')], db_index=True, default='DRAFT', max_length=32, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_products', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_to, validators=[products.validators.validate_product_image], verbose_name='تصویر')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('sort_order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['source_type', 'status'], name='products_src_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('suggested_price__gte', 0), ('suggested_price__isnull', True), _connector='OR'), name='products_product_suggested_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('suitable_price__gte', 0), ('suitable_price__isnull', True), _connector='OR'), name='products_product_suitable_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('source_type', 'product_code'), name='products_product_source_type_product_code_key'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='products_productimage_sort_order_gte_0'),
        ),
    ]
