# Generated by Django 5.2.9 on 2026-08-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'permissions': (('review_product', 'Can review product'),), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
