# Generated by Django 5.1.6 on 2026-09-20 06:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_assigned_expert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_inspection_done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='بازدید نهایی شده'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_all_prices',
            field=models.BooleanField(default=False, verbose_name='تمام قیمت\u200cها وارد شده'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_initial_info',
            field=models.BooleanField(default=False, verbose_name='اطلاعات اولیه وارد شده'),
        ),
        migrations.AddField(
            model_name='product',
            name='to_buy',
            field=models.BooleanField(db_index=True, default=False, verbose_name='خریداری شود'),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='نام حراجی')),
                ('source_house', models.CharField(choices=[('CHRISTIES', "Christie's"), ('SOTHEBYS', "Sotheby's"), ('BONHAMS', 'Bonhams'), ('OTHER', 'سایر حراجی\u200cها')], db_index=True, default='OTHER', max_length=32, verbose_name='خانه حراجی')),
                ('start_date', models.DateField(db_index=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='مکان برگزاری')),
                ('currency', models.CharField(choices=[('USD', 'دلار آمریکا (USD)'), ('EUR', 'یورو (EUR)'), ('GBP', 'پوند انگلیس (GBP)'), ('AED', 'درهم امارات (AED)'), ('IRR', 'ریال ایران (IRR)'), ('OTHER', 'سایر')], default='USD', max_length=16, verbose_name='واحد پول')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='درصد کمیسیون یا Buyer Premium حراجی (مثلاً 25 برای 25%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='درصد کمیسیون')),
                ('status', models.CharField(choices=[('UPCOMING', 'به زودی'), ('ONGOING', 'در حال برگزاری'), ('ENDED', 'پایان یافته')], db_index=True, default='UPCOMING', max_length=32, verbose_name='وضعیت برگزاری')),
                ('total_lots', models.PositiveIntegerField(default=0, help_text='تعداد کل آثار ثبت\u200cشده در کاتالوگ حراجی', validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد کل آثار')),
                ('entered_lots_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد آثار وارد شده')),
                ('cancelled_lots_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد انصرافی')),
                ('expert_lots_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد کارشناسی')),
                ('notable_lots_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد قابل توجه')),
                ('to_buy_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد مواردی که باید خریداری شود')),
                ('initial_info_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مواردی که اطلاعات اولیه آن وارد شده است')),
                ('all_prices_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مواردی که تمام قیمت\u200cهای آن وارد شده است')),
                ('final_inspection_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مواردی که بازدید نهایی شده\u200cاند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_auctions', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_auctions', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط')),
            ],
            options={
                'verbose_name': 'حراجی',
                'verbose_name_plural': 'حراجی\u200cها',
                'ordering': ('-start_date', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.auction', verbose_name='حراجی مرتبط'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'start_date'], name='auction_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['source_house', 'status'], name='auction_house_status_idx'),
        ),
    ]
